---

- name: restart app
  command: "{{ app_home }}/bin/circusctl restart {{ app_name }}"

- name: restart nginx
  sudo: yes
  action: service name=nginx state=restarted

- name: reload circusd
  command: "{{ app_home }}/bin/circusctl reloadconfig"
