---

- name: restart app
  command: "{{ app_home }}/bin/circusctl restart {{ app_name }}"

- name: restart nginx
  sudo: yes
  action: service name=nginx state=restarted

- name: reload circusd
  action: service name=circusd state=reloaded

- name: start circusd
  action: service name=circusd state=started

- name: restart circusd
  action: service name=circusd state=restarted

- name: reload systemctl
  command: systemctl daemon-reload
  sudo: yes
